### PR TITLE
Make volume ensurable

### PR DESCRIPTION
**Pull request by glorpen**
#### Pull Request (PR) description
Adds ensure parameter for `gluster::volume` type with support for `present` and `absent` values.

#### This Pull Request (PR) fixes the following issues
n/a

Since this diff could be hard to read, it was enough to add 2x `if $ensure == 'present'` and 1x `exec { "gluster stop and remove ${title}":` :)

### CODE REVIEW

**Comment by glorpen** [comment]
@ekohl Sorry for pinging you out of the blue but could you look at 3 waiting PRs? #215 , this one and #220.

**Comment by ekohl** [comment]
Looks good, but needs a rebase to fix the merge conflict. Mind also squashing the commits while you're at it?

**Comment by glorpen** [comment]
@ekohl done

**Review by ekohl — APPROVED** [review]
Thanks!

> Since this diff could be hard to read, it was enough to add 2x `if $ensure == 'present'` and 1x `exec { "gluster stop and remove ${title}":` :)

Git and Github also have options to hide whitespace changes. They showed the same thing.

**Pull request merged**
