### PR TITLE
Sanitize values of GlusterFS options

### PR DESCRIPTION
**Pull request by zstyblik**
Commit sanitizes values of options returned by `gluster volume info`. There
seems to be inconsistency between values you set and values you get from command
mentioned earlier. This leads to enforcing options over and over again, because
`true` isn't ever going to match `on`.
Unfortunately, doing so leads to leaking memory in GlusterFS. Last, but not least, we
shouldn't enforce settings which haven't changed over and over again anyway
anyhow.

### CODE REVIEW

**Comment by zstyblik** [comment]
Is there something else to be done to get this merged?

Thanks.

**Comment by tux-o-matic** [comment]
@zstyblik that is indeed an annoying problem, thanks.
I think you need to rebase because of manifests/repo/apt.pp which didn't pass tests until after you did this PR.

**Comment by zstyblik** [comment]
I did rebase and whatever CI asked, although I believe the use of `unless` is strongly discouraged.

**Comment by bastelfreak** [comment]
THanks for the PR @zstyblik, are you abel to add tests as well?

**Comment by zstyblik** [comment]
@bastelfreak, unfortunately rspec is beyond my understanding. :/

**Comment by zstyblik** [comment]
@bastelfreak, unfortunately rspec is beyond my understanding. :/

**Comment by juniorsysadmin** [comment]
Seems reasonable but would like some tests

**Pull request closed without merging**
