### PR TITLE
Add ubuntu support

### PR DESCRIPTION
**Pull request by shieldwed**
#### Pull Request (PR) description
Add support to install Gluster from their [PPA](https://launchpad.net/~gluster) to get more up-to-date versions than included in Ubuntu universe repository.

### CODE REVIEW

**Comment by shieldwed** [comment]
How can I move this PR forward?

**Comment by smortex** [comment]
Regarding the "Puppet 6 - Ubuntu 18.04" failure, you can apply this (same issue with another module, mind adjusting the comment):
https://github.com/voxpupuli/puppet-puppetboard/commit/7366b4e3a5e29c1dd769a31caf48d75a2b2d648f

Debian 9 has reached EOL, if we can't fix it we can remove it.  But it would be best to fix Debian 9, then in another PR add support for current Debian versions, and last in another PR drop support for Debian 9.

**Comment by shieldwed** [comment]
Is there anything more I can do to move this PR forward?

**Review by smortex — APPROVED** [review]
This looks good to me, at least as far as puppet code is concerned because I have no knowledge of gluster.  Nobody have complained so it's probably okay to merge this!

**Pull request merged**
