### PR TITLE
Switched YUM repo to use the new CentOS Storage group repository

### PR DESCRIPTION
**Pull request by tux-o-matic**
This is to fix the problem described in #63 and #68.
The GlusterFS community (and well RedHat) moved the responsibility of providing RPMs for EL systems to a new SIG group in the CentOS community.

Since the new CentOS repo has a slightly diferent structure than the GlusterFS repo used for systems using APT, I had to introduce a new parameter named "release" (explained in the README). This should be used on EL systems for running older GlusterFS versions and combined iwth the existing "version" parameter

While at it, I simplified the code handling the YUM repo and updated some parts of the documentation related to repos which were out dated.

The name of the Yumrepo resource remained the same in order to update its settings for systems already using this module. If installed by the CentOS rpm 'centos-release-gluster', the name of the repo configured on the system would differ [repo](https://github.com/CentOS-Storage-SIG/centos-release-gluster38/blob/master/CentOS-Gluster-3.8.repo)

### CODE REVIEW

**Comment by tux-o-matic** [comment]
We might want to work update the test case for unsupported architecture.
The Puppet code will raise an error when unsupported and the test scenario doesn't handle that nicely.

**Comment by tux-o-matic** [comment]
@bastelfreak could you or any other community members look into this PR?
The module can no longer install GlusterFS on OS relaying on YUM to get the packages since the GlusterFS community moved the repo to CentOS managed servers.

**Comment by bastelfreak** [comment]
Hi, in general the PR looks good. Can you take a look at the test for the architecture?

**Comment by tux-o-matic** [comment]
Fixed. just took a little re-phrasing of the message in the error raised on unsupported architecture.

**Comment by bastelfreak** [comment]
Thanks!

**Pull request merged**
