### PR TITLE
Updated repo URI

### PR DESCRIPTION
**Pull request by pcastellazzi**
The RHEL directory was removed some time ago, i updated the URI to reflect this change.

### CODE REVIEW

**Comment by skpy** [comment]
Using this, I get a failure trying to install glusterfs-server on CentOS 7:
```
Info: Applying configuration version '1448982610'
Error: Execution of '/bin/yum -d 0 -e 0 -y install glusterfs-server' returned 1: Error: Package: glusterfs-server-3.7.6-1.el7.x86_64 (glusterfs-x86_64)
           Requires: liburcu-cds.so.1()(64bit)
Error: Package: glusterfs-server-3.7.6-1.el7.x86_64 (glusterfs-x86_64)
           Requires: liburcu-bp.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Error: /Stage[main]/Gluster::Install/Package[glusterfs-server]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install glusterfs-server' returned 1: Error: Package: glusterfs-server-3.7.6-1.el7.x86_64 (glusterfs-x86_64)
           Requires: liburcu-cds.so.1()(64bit)
Error: Package: glusterfs-server-3.7.6-1.el7.x86_64 (glusterfs-x86_64)
           Requires: liburcu-bp.so.1()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
I don't see any indication that `libucru-cds` or `libucru-bp` are easily installable on CentOS.  How did you get past this?

**Comment by pcastellazzi** [comment]
It seems you are missing EPEL. (`rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm`). The package with the library on my system is userspace-rcu. Also i am using AWS not CentOS, if you keep having problems let me know and i will try this on a CentOS box until it works as expected.

**Comment by skpy** [comment]
Ah yes, I don't install EPEL as a matter of course, and I didn't realize that Gluster now requires EPEL packages.  Do you think this module should ensure that the EPEL repo is enabled, or should that be left to the administration to manage elsewhere in their Puppet configurations?

**Comment by skpy** [comment]
@pcastellazzi can you please also replace the [GPG key](https://github.com/covermymeds/puppet-gluster/blob/master/files/RPM-GPG-KEY-gluster.pub) with the [new one](http://download.gluster.org/pub/gluster/glusterfs/3.7/LATEST/NEW_PUBLIC_KEY.README) from the Gluster repo?
```
Error: Execution of '/bin/yum -d 0 -e 0 -y install glusterfs-server' returned 1: warning: /var/cache/yum/x86_64/7/glusterfs-x86_64/packages/glusterfs-client-xlators-3.7.6-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID d5dc52dc: NOKEY
Importing GPG key 0x4AB22BB3:
 Userid     : "Gluster Packager <glusterpackager@download.gluster.org>"
 Fingerprint: 591a 0fd2 7e0f 1cba 27c7 1b7d dde4 5e09 4ab2 2bb3
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-gluster.pub


Public key for glusterfs-client-xlators-3.7.6-1.el7.x86_64.rpm is not installed
```

Or provide some way to fetch the GPG key from the repository and install it automatically?

**Comment by pcastellazzi** [comment]
I am not sure if messing with the OS repositories is a good idea, mostly because a user may want to use an internal copy, or a copy from his cloud provider, or just a different public mirror. I think it is best to document the dependancy and to provide an example of how to fulfill it with the default repo.

**Comment by skpy** [comment]
@pcastellazzi  I've just transferred this module to the [Puppet Community](https://github.com/puppet-community) organization.  Your PR was transferred, too; but please update your bookmarks and your `.git/config` as necessary.  **Thanks!**

**Comment by nibalizer** [comment]
One idea is to add 'include epel' to the module. The epel module is well known and well trusted.

**Comment by igalic** [comment]
or you could uninstall pygpgme, thus disabling gpg checks for rpm

**Comment by igalic** [comment]
:+1:, what @nibalizer said

**Comment by jyaworski** [comment]
Closing, per #35.

**Pull request closed without merging**
