### PR TITLE
Allow volumes without replicas

### LINKED ISSUE #88: Creating volume without replication
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-3.8.7-1
- Ruby: ruby-2.0.0
- Distribution: RHEL 7
- Module version: Latest

### What are you seeing
 If I don't provide replica option, puppet does not create volume  
### What behaviour did you expect instead
I changed volume.pp and then it worked
 if $replica {
    if ! is_integer( $replica ) {
      fail("Replica value ${replica} is not an integer")
    } else {
      $_replica = "replica ${replica}"
    }
   } else {            # This else part was added
      $_replica = ''
  }

### PR DESCRIPTION
**Pull request by glorpen**
This PR is strongly based on work in #92 but it is updated to current master and with one more test.

Fixes #88 
Closes #92

### CODE REVIEW

**Comment by glorpen** [comment]
Not sure if it is what you wanted;
`$options` (and `$_options`) can be undef or array and is expected by code to be just that, I would only force string content with parameter type - `Optional[Array[String]]` but then `gluster::volume::setting` has non-typed parameter.

**Comment by ekohl** [comment]
I meant https://github.com/voxpupuli/puppet-gluster/blob/805e649702e09dc7be2d02d52ff622b9f990c422/manifests/volume.pp#L80

**Comment by glorpen** [comment]
well, there was a bug :)

**Comment by ekohl** [comment]
I had a look and I think that https://github.com/voxpupuli/puppet-gluster/pull/169 cleans up it a lot by using Puppet 4 language constructs. Haven't actually tested it so let's see if the tests pass :)

**Comment by glorpen** [comment]
@ekohl can we merge this? I think it would be nice since this PR contains changes from Dec 2016.

**Comment by ekohl** [comment]
Thanks!

**Comment by glorpen** [comment]
Big thanks :)

**Pull request merged**
