### PR TITLE
Strip missing_brick check in gluster::volume

### PR DESCRIPTION
**Pull request by rauchrob**
Before, Gluster volume creation is skipped when `$missing_bricks` is not empty. With this behaviour, it is impossible to create volumes with bricks whose hostname parts do not match the gluster nodes FQDN (or, more precisely, are not contained in the `$pool_members` array). This can be necessary for example when the Gluster Nodes have multiple Interfaces and different volumes are to be accessed by clients on different interfaces.

Moreover, Gluster will complain anyway, if one of the specified bricks is not available, making the `Exec["gluster create volume ${title}"]` visibly fail. I see no reason why we should do this type of validation, which should be and is already done at the Gluster side.

### CODE REVIEW

**Comment by bastelfreak** [comment]
hi @rauchrob, also thanks for this contribution. could you rebase here too and maybe add tests for that?

**Comment by rauchrob** [comment]
There are still some strict variable related issues around, which are now being detected by my simple `gluster::volume` specs...

**Comment by bastelfreak** [comment]
Hi, this is a bit strange, because the last release we did was successful: https://travis-ci.org/voxpupuli/puppet-gluster/builds/129547812

**Comment by bastelfreak** [comment]
okay, nevermind, we didn't test that correctly in the past. This could fix it?:
```puppet

if $options {
    validate_array( $options )
    $_options = sort( $options )
} else {
  $_options  = false
}
```

**Comment by rauchrob** [comment]
@bastelfreak I see no quick-fix. I will have a closer look on this soon. IMHO the `gluster::volume` type needs serious refactoring and better unit tests.

**Comment by bastelfreak** [comment]
Hello. I'm going to close this PR due to inactivity. Please reopen and rebase it if you're still interested in it.

**Pull request closed without merging**
