### PR TITLE
Fixed logic for single node gluster servers

### PR DESCRIPTION
**Pull request by glorpen**
When trying to configure Gluster on single node no `gluster::volume` exec's were applied, no volume created, etc.

This behavior was created by assumptions on `gluster_peer_count` and `gluster_peer_list` facts as it is empty when operating on single node.
Second thing was that check for missing bricks (in `gluster::volume`) always failed because of empty `gluster_peer_list` - no peers, no volumes :). Fortunately there already was https://github.com/voxpupuli/puppet-gluster/pull/125 which seemed as good fit. Since it worked, It's now merged into this PR.

Fixes https://github.com/voxpupuli/puppet-gluster/issues/6 , but since that time behaviour has changed a little - no duplicates, just nothing :).

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @glorpen, thanks for the PR. Can you please rebase against our latest master branch?

**Comment by glorpen** [comment]
@bastelfreak done

**Comment by glorpen** [comment]
@bastelfreak ping

**Comment by bastelfreak** [comment]
Thanks for the fix @glorpen !

**Pull request merged**
