### PR TITLE
Pin rake to avoid rubocop/rake 11 incompatibility

### PR DESCRIPTION
**Pull request by roidelapluie**
See https://github.com/voxpupuli/modulesync_config/pull/93

This commit updates the module to our latest modulesync configuration.

### CODE REVIEW

**Comment by dhoppe** [comment]
The [Travis CI build](https://travis-ci.org/voxpupuli/puppet-gluster/jobs/115303315#L343) is failing, because the fact ```architecture``` should have the values _x86_64_ or _i386_, but the Docker image _Ubuntu 14.04_ returns _amd64_.

**Comment by jyaworski** [comment]
We no longer need to pin, because modulesync_config and rubocop were both updated.

**Comment by juniorsysadmin** [comment]
Superseded by #46

**Comment by juniorsysadmin** [comment]
@roidelapluie Please delete the branch. I've also accidentally pushed a branch to the upstream repo and not my own fork before, but it's not a good habit to get into. (Unless it's say a long running branch, and you want others to commit to it)

**Pull request closed without merging**
