### PR TITLE
Fixes and tests for strict variables

### PR DESCRIPTION
**Pull request by alexjfisher**

### CODE REVIEW

**Comment by alexjfisher** [comment]
Looks like build is failing due to a recent stdlib regression.

**Comment by alexjfisher** [comment]
Supercedes https://github.com/voxpupuli/puppet-gluster/pull/83 and https://github.com/voxpupuli/puppet-gluster/pull/84

**Comment by sammcj** [comment]
Awesome, thanks all, will test and report back.

**Comment by sammcj** [comment]
Looks good all, was able to implement the latest release to master (note: there is no tag, you might want to update this to 2.2.3 or something) without any problems.

**Comment by alexjfisher** [comment]
@sammcj https://github.com/voxpupuli/puppet-gluster/pull/90 Enjoy!

**Pull request merged**
