### PR TITLE
Fixed CentOS storage SIG GPG key (issue #63 #68) and server package name

### PR DESCRIPTION
**Pull request by mkmet**
Fixed issues with GPG key and server package name which prevented installation of packages on CentOS 7. (issue #63 #68)

### CODE REVIEW

**Comment by bastelfreak** [comment]
Hi @mkmet, could you please add a spec test for the glusterfs-server package resource?

**Comment by tux-o-matic** [comment]
@bastelfreak the [YUM spec](https://github.com/voxpupuli/puppet-gluster/blob/master/spec/classes/repo_yum_spec.rb) is quite out of date now.

**Comment by bastelfreak** [comment]
Uff. Are you able to update it?

**Comment by tux-o-matic** [comment]
@bastelfreak Couldn't the spec be a separate issue/PR? Cause this GPG key issue is a blocking issue for people wishing to setup new GlusterFS nodes.

**Comment by mkmet** [comment]
I can't look at it right now because of my workload. However I'll look at it in the future if somebody won't do it before me.

**Pull request merged**
