### PR TITLE
modulesync 1.9.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by wyardley** [comment]
@ekohl @bastelfreak: Seems like recent requests are getting merged with the same failing acceptance test. Does anyone know whether it's a legitimate failure, and can we either mark that test as pending or fix it?

**Comment by ekohl** [comment]
@wyardley if master also fails (which I think it does) then we should start by marking it pending.

**Comment by wyardley** [comment]
@ekohl @bastelfreak the service literally doesn't start, I'm not sure how the service is configured, but the system seems to be using systemd; there's no unit file that I can see, and the package (despite its description) doesn't seem to drop down an init script or anything related to services. Checked the post script too, nothing obvious there either.
```
root@debian-82-x64:~# dpkg -L glusterfs-server
/.
/var
/var/lib
/var/lib/glusterd
/var/lib/glusterd/hooks
/var/lib/glusterd/hooks/1
/var/lib/glusterd/hooks/1/gsync-create
/var/lib/glusterd/hooks/1/gsync-create/post
/var/lib/glusterd/hooks/1/gsync-create/post/S56glusterd-geo-rep-create-post.sh
/etc
/etc/glusterfs
/etc/glusterfs/glusterd.vol
/usr
/usr/sbin
/usr/sbin/gcron.py
/usr/sbin/gluster
/usr/sbin/snap_scheduler.py
/usr/sbin/glfsheal
/usr/share
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/glusterfs-server
/usr/share/doc
/usr/share/doc/glusterfs-server
/usr/share/doc/glusterfs-server/copyright
/usr/share/doc/glusterfs-server/changelog.Debian.gz
/usr/share/doc/glusterfs-server/changelog.gz
/usr/share/glusterfs
/usr/share/glusterfs/scripts
/usr/share/glusterfs/scripts/generate-gfid-file.sh
/usr/share/glusterfs/scripts/gsync-upgrade.sh
/usr/share/glusterfs/scripts/gsync-sync-gfid
/usr/share/glusterfs/scripts/post-upgrade-script-for-quota.sh
/usr/share/glusterfs/scripts/slave-upgrade.sh
/usr/share/glusterfs/scripts/get-gfid.sh
/usr/share/glusterfs/scripts/pre-upgrade-script-for-quota.sh
/usr/share/man
/usr/share/man/man8
/usr/share/man/man8/gluster.8.gz
/usr/share/man/man8/glusterd.8.gz
/usr/bin
/usr/bin/glusterfind
/usr/sbin/gfind_missing_files
/usr/sbin/glusterd
root@debian-82-x64:~# systemctl list-unit-files | grep glust
root@debian-82-x64:~# 
```

**Comment by ekohl** [comment]
@wyardley looking at https://packages.debian.org/jessie/amd64/glusterfs-server/filelist then there is a service file in init.d. Which version is it installing?

**Comment by bastelfreak** [comment]
@ekohl the module configures the glusterfs repos, their 3.8 package for debian 8 is broken and doesn't contain a svsy nor a systemd unit file.  I tested the 3.12 release and that is working. I'm currently debugging through the different releases.

**Comment by wyardley** [comment]
FWIW, in Vagrant, if I remove the gluster repo, it does seem like I can restart the service.
So, in lieu of dropping Debian 8 support, what about having the acceptance tests run with the `repo` param set to `false`?

```
root@debian-82-x64:/tmp# service glusterfs-server restart
root@debian-82-x64:/tmp# 
root@debian-82-x64:/tmp# 
root@debian-82-x64:/tmp# ps -ef | grep gluster
root      8389     1  0 16:03 ?        00:00:00 /usr/sbin/glusterd -p /var/run/glusterd.pid
root      8620  6108  0 16:03 pts/0    00:00:00 grep gluster
```

**Comment by wyardley** [comment]
FWIW, this passes for me... personally, I like when vendor package is a module's default... thoughts?

```
diff --git a/spec/acceptance/client_spec.rb b/spec/acceptance/client_spec.rb
index 2eab1f1..350f5b4 100644
--- a/spec/acceptance/client_spec.rb
+++ b/spec/acceptance/client_spec.rb
@@ -6,7 +6,7 @@ describe 'gluster client' do
       pp = <<-EOS
 
        class { 'gluster':
-         repo    => true,
+         repo    => false,
          client  => true,
          server  => false,
          release => '3.9',
diff --git a/spec/acceptance/server_spec.rb b/spec/acceptance/server_spec.rb
index 0b92204..921ab59 100644
--- a/spec/acceptance/server_spec.rb
+++ b/spec/acceptance/server_spec.rb
@@ -6,7 +6,7 @@ describe 'gluster server' do
       pp = <<-EOS
 
        class { 'gluster':
-         repo    => true,
+         repo    => false,
          client  => false,
          server  => true,
          release => '3.9',
```

**Comment by ekohl** [comment]
@wyardley +1 for preferring the vendor versions. I think we should change the default in params.pp too though that might be a major version bump.

**Comment by bastelfreak** [comment]
I will close this and do a new modulesync

**Pull request closed without merging**
